export const SELECT_SHOW = 'SELECT_SHOW';
export const START_FETCHING_SHOWS = 'START_FETCHING_SHOWS';
export const SUCCESS_FETCHING_SHOWS = 'SUCCESS_FETCHING_SHOWS';
export const ERROR_FETCHING_SHOWS = 'ERROR_FETCHING_SHOWS';
export const INCREASE_API_INDEX = 'INCREASE_API_INDEX';
export const DECREASE_API_INDEX = 'DECREASE_API_INDEX';
